// <auto-generated />
namespace TourismManagementSystem.MigrationsBusiness
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBookings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBookings));
        
        string IMigrationMetadata.Id
        {
            get { return "202601141315161_AddBookings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
