// <auto-generated />
namespace TourismManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddProfileImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProfileImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202601140718431_AddProfileImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
